controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
fallback:
    path: /{url}
    controller: App\Controller\FallbackController::index
    requirements:
        url: .+
